# Generated by Django 5.2.9 on 2025-12-21 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alumno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_control", models.CharField(max_length=20, unique=True)),
                ("curp", models.CharField(max_length=18, unique=True)),
                ("nombre_completo", models.CharField(max_length=255)),
                (
                    "grado",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "1"),
                            (2, "2"),
                            (3, "3"),
                            (4, "4"),
                            (5, "5"),
                            (6, "6"),
                        ]
                    ),
                ),
                (
                    "grupo",
                    models.CharField(choices=[("A", "A"), ("B", "B")], max_length=1),
                ),
                (
                    "turno",
                    models.CharField(
                        choices=[("M", "Matutino"), ("V", "Vespertino")], max_length=1
                    ),
                ),
                (
                    "especialidad",
                    models.CharField(
                        choices=[
                            ("PROG", "Programación"),
                            ("OFI", "Ofimática"),
                            ("CONT", "Contabilidad"),
                            ("CIA", "Comercio Internacional y Aduanas"),
                            ("ENF", "Enfermería"),
                            ("IA", "Inteligencia Artificial"),
                            ("CIB", "Ciberseguridad"),
                            ("ARH", "Administración de Recursos Humanos"),
                        ],
                        max_length=5,
                    ),
                ),
                ("direccion", models.TextField(blank=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("telefono_contacto", models.CharField(blank=True, max_length=20)),
                ("nombre_tutor", models.CharField(blank=True, max_length=255)),
                ("telefono_tutor", models.CharField(blank=True, max_length=20)),
                ("email_tutor", models.EmailField(blank=True, max_length=254)),
                (
                    "foto",
                    models.ImageField(
                        blank=True, null=True, upload_to="alumnos/fotos/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
