# Generated by Django 5.2.9 on 2025-12-23 02:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("face_recognition", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="attendance_date",
            field=models.DateField(
                db_index=True, default=django.utils.timezone.localdate
            ),
        ),
    ]
